Return-Path: <imaptest73@gmail.com>
X-Original-To: andrea.parodi@ebansoftware.net
Delivered-To: andrea.parodi@ebansoftware.net
Received: by hosting.ebansoftware.com (Postfix, from userid 1002)
	id 0265924A60; Sat, 12 Oct 2013 20:19:29 +0200 (CEST)
Message-ID: <52598EA6.4080401@gmail.com>
Date: Sat, 12 Oct 2013 20:02:14 +0200
From: "imaptest73@gmail.com" <imaptest73@gmail.com>
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:17.0) Gecko/20130801 Thunderbird/17.0.8
MIME-Version: 1.0
To: andrea.parodi@ebansoftware.net
Subject: test with attachments
Content-Type: multipart/mixed;
 boundary="------------080405040204090506050605"

This is a multi-part message in MIME format.
--------------080405040204090506050605
Content-Type: text/plain; charset=ISO-8859-15; format=flowed
Content-Transfer-Encoding: 7bit

this is the body

--------------080405040204090506050605
Content-Type: text/plain; charset=windows-1252;
 name="test.txt"
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename="test.txt"

dGhpcyBpcyBhIHRlc3Q=
--------------080405040204090506050605--
