FCC: imap://imaptest73%40gmail.com@imap.googlemail.com/[Gmail]/Posta inviata
X-Identity-Key: id2
X-Account-Key: account5
Message-ID: <52596D4D.4020507@gmail.com>
Date: Sat, 12 Oct 2013 17:39:57 +0200
From: "imaptest73@gmail.com" <imaptest73@gmail.com>
X-Mozilla-Draft-Info: internal/draft; vcard=0; receipt=0; DSN=0; uuencode=0
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:17.0) Gecko/20130801 Thunderbird/17.0.8
MIME-Version: 1.0
Subject: this is a test
Content-Type: text/html; charset=ISO-8859-15
Content-Transfer-Encoding: 7bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-15">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <br>
  </body>
</html>
